name: "Visibility Test"
description: "Auto test for plugin sermant-visibility"
runs:
  using: "composite"
  steps:
    - name: visibility-entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/dubbo-visibility
    - name: package visibility dubbo 2.6.0 tests
      shell: bash
      if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions == '0'
      run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests -P260 --file sermant-integration-tests/dubbo-test/pom.xml
    - name: package visibility dubbo 2.6.x tests
      shell: bash
      if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions != '0'
      run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
    - name: package visibility dubbo 2.7.x tests
      shell: bash
      if: matrix.dubbo-version == '2-7'
      run: mvn package -Ddubbo.version=2.7.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
    - name: start visibility provider service
      shell: bash
      env:
        SERVER_PORT: 28054
        DUBBO_PROTOCOL_PORT: 28854
        VISIBILITY_SERVICE_FLAG: true
        VISIBILITY_CONFIG_START_FLAG: true
        AGENT_CONFIG_SERVICE_BLACK_LIST: com.huaweicloud.sermant.implement.service.tracing.TracingServiceImpl
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-provider  -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-provider/target/dubbo-integration-provider.jar > ${{ env.logDir }}/visibility-provider.log 2>&1 &
    - name: start visibility consumer service
      shell: bash
      env:
        SERVER_PORT: 28050
        DUBBO_PROTOCOL_PORT: 28850
        VISIBILITY_SERVICE_VERSION: 12345
        VISIBILITY_CONFIG_START_FLAG: true
        AGENT_CONFIG_SERVICE_BLACK_LIST: com.huaweicloud.sermant.implement.service.tracing.TracingServiceImpl
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-consumer/target/dubbo-integration-consumer.jar > ${{ env.logDir }}/visibility-consumer.log 2>&1 &
    - name: start visibility backend service
      shell: bash
      run: |
        nohup java -jar sermant-agent-${{ env.sermantVersion }}/server/sermant/sermant-backend-1.0.0.jar > ${{ env.logDir }}/visibility-backend.log 2>&1 &
    - name: waiting for visibility services start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28050/actuator/health 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28054/actuator/health 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8900/visibility/getCollectorInfo 120
    - name: visibility test
      shell: bash
      env:
        TEST_TYPE: visibility
      run: mvn  test --file sermant-integration-tests/dubbo-test/pom.xml
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: dubbo
    - name: upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: visibility-(${{ matrix.dubbo-version }}-${{ matrix.dubbo-versions }})-logs
        path: |
          ./*.log
          ./logs/**/*.log
        if-no-files-found: warn
        retention-days: 2
